# Generated by Django 4.0.2 on 2022-04-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
