# Generated by Django 4.0.2 on 2022-04-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assignment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='assignment',
            field=models.ManyToManyField(to='api.Assignment'),
        ),
    ]
