# Generated by Django 4.0.2 on 2022-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_assignment_assigned_remove_assignment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='assignment',
            field=models.ManyToManyField(related_name='comment', to='api.Assignment'),
        ),
    ]
